#! /usr/bin/env python
# encoding: utf-8
#
# Flare Bootscript Generator
#

import argparse
import os
import sys
import zlib

def run(args=sys.argv):
    argsp = argparse.ArgumentParser(prog='bootscripter',
                                    description='Flare bootscript generator')
    argsp.add_argument('--exe',
                       help='Path to executable to boot',
                       type=str,
                       default=None,
                       required=True)
    argsp.add_argument('--path',
                       help='Path to file on FAT partition on SD card',
                       type=str,
                       default=None,
                       required=True)
    argsp.add_argument('--output',
                       help='Output file',
                       type=str,
                       default='flare-0')

    opts = argsp.parse_args(args[1:])

    if not os.path.exists(opts.exe):
        raise RuntimeError('Executable file does not exist')

    exe_crc = 0;
    for eachline in open(opts.exe, 'rb'):
        exe_crc = zlib.crc32(eachline, exe_crc)

    bs = opts.path
    bs += '\n'
    bs += os.path.basename(opts.exe)
    bs += ','
    bs += '{:08x}'.format(exe_crc)
    bs += '\n'

    with open(opts.output, 'w') as bs_file:
        bs_file.write(bs)
        bs_file.write('{:08x}'.format(zlib.crc32(bs.encode(), 0)))
        bs_file.write('\n')


if __name__ == "__main__":
    sys.exit(run())
