#! /usr/bin/env python
# encoding: utf-8
#
# Flare UART Driver
#

import builditems

sources = {
    'default': [
        'outbyte.c',
        'inbyte.c',
    ],
    'versal': [
        'versal-uart.c',
    ],
    'zynqmp': [
        'zynqmp-uart.c',
    ],
    'zynq7000': [
        'zynq7000-uart.c',
    ]
}

includes = {'default': ['..'], 'versal': [], 'zynqmp': [], 'zynq7000': []}

defines = {'default': [], 'versal': [], 'zynqmp': [], 'zynq7000': []}

cflags = {'default': [], 'versal': [], 'zynqmp': [], 'zynq7000': []}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_uart_driver',
                features='c',
                source=builditems.get_items(bld, sources),
                includes=builditems.get_includes(bld, includes),
                cflags=builditems.get_cflags(bld, cflags),
                defines=builditems.get_defines(bld, defines))
