#! /usr/bin/env python
# encoding: utf-8
#
# Flare AARCH64 MMU Support

import builditems

sources = {
    'default': [],
    'versal': [
        'aarch64-cache.c',
        'versal-mmu.c',
    ],
    'zynqmp': [
        'aarch64-cache.c',
        'zynqmp-mmu.c',
    ],
    'zynq7000': []
}

includes = {
    'default': [],
    'versal': [
        '..',
    ],
    'zynqmp': [
        '..',
    ],
    'zynq7000': []
}

defines = {'default': [], 'versal': [], 'zynqmp': [], 'zynq7000': []}

cflags = {'default': [], 'versal': [], 'zynqmp': [], 'zynq7000': []}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_aarch64_mmu',
                features='c',
                source=builditems.get_items(bld, sources),
                includes=builditems.get_includes(bld, includes),
                cflags=builditems.get_cflags(bld, cflags),
                defines=builditems.get_defines(bld, defines))
