#! /usr/bin/env python
# encoding: utf-8
#
# Flare WatchDog Driver
#

import builditems

sources = {
    'default': [],
    'versal': [],
    'zynqmp': [
        'empty-wdog.c',
        'wdog-empty.c',
    ],
    'zynq7000': ['zynq7000-wdog.c', 'wdog-flare_1.c']
}

includes = {'default': ['..'], 'versal': [], 'zynqmp': [], 'zynq7000': []}

defines = {'default': [], 'versal': [], 'zynqmp': [], 'zynq7000': []}

cflags = {'default': [], 'versal': [], 'zynqmp': [], 'zynq7000': []}


def init(ctx):
    pass


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.objects(target='flare_wdog_driver',
                features='c',
                source=builditems.get_items(bld, sources),
                includes=builditems.get_includes(bld, includes),
                cflags=builditems.get_cflags(bld, cflags),
                defines=builditems.get_defines(bld, defines))
