#! /usr/bin/env python
# encoding: utf-8
#
# Flare Driver Support
#

import buildcontrol

directories = [
    'flash',
    'jffs2',
    'zlib',
    'leds',
    'md5',
    'libc',
    'uart',
    'timer',
    'wdog',
    'io',
    'gpio',
    'power-switch',
    'slcr',
    ]

def init(ctx):
    buildcontrol.recurse(ctx, directories)

def options(opt):
    buildcontrol.recurse(opt, directories)

def configure(conf):
    buildcontrol.recurse(conf, directories)

def build(bld):
    buildcontrol.recurse(bld, directories)
    bld.stlib(target='flare_drivers',
              features='c',
              source=['drivers.c'],
              use=['flare_flash_driver',
                   'flare_jffs2_driver',
                   'flare_zlib_driver',
                   'flare_leds_driver',
                   'flare_md5_driver',
                   'flare_libc_driver',
                   'flare_uart_driver',
                   'flare_timer_driver',
                   'flare_wdog_driver',
                   'flare_io_driver',
                   'flare_gpio_driver',
                   'flare_power_switch_driver',
                   'flare_slcr_driver',
                   ])
