/*
 * Copyright 2024 Contemporary Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

.global aarch64_handoff

aarch64_handoff:
  mov X1, XZR
  mov X2, XZR
  mov X3, XZR
  mov X4, XZR
  mov X5, XZR
  mov X6, XZR
  mov X7, XZR
  mov X8, XZR
  mov X9, XZR
  mov X10, XZR
  mov X11, XZR
  mov X12, XZR
  mov X13, XZR
  mov X14, XZR
  mov X15, XZR
  mov X16, XZR
  mov X17, XZR
  mov X18, XZR
  mov X19, XZR
  mov X20, XZR
  mov X21, XZR
  mov X22, XZR
  mov X23, XZR
  mov X24, XZR
  mov X25, XZR
  mov X26, XZR
  mov X27, XZR
  mov X28, XZR
  mov X29, XZR
  mov X30, XZR
  br  x0
