#! /usr/bin/env python
# encoding: utf-8
#
# Flare Bootloader
#

import buildcontrol
import builditems

directories = [
    'driver',
    'fs',
    'arch',
    'board',
]

sources = {
    'default': [
        'boot-buffer.c',
        'boot-factory-config.c',
        'boot-load.c',
        'boot-script.c',
        'datasafe.c',
        'factory-boot.c',
        'reset.c',
    ],
    'versal': [],
    'zynqmp': [],
    'zynq7000': []
}

includes = {
    'default': [
        '.',
    ],
    'versal': [],
    'zynqmp': [],
    'zynq7000': []
}

defines = {'default': [], 'versal': [], 'zynqmp': [], 'zynq7000': []}

cflags = {'default': [], 'versal': [], 'zynqmp': [], 'zynq7000': []}


def init(ctx):
    buildcontrol.recurse(ctx, directories)


def options(opt):
    buildcontrol.recurse(opt, directories)


def configure(conf):
    buildcontrol.recurse(conf, directories)


def build(bld):
    buildcontrol.recurse(bld, directories)
    bld.stlib(target='flare',
              features='c',
              source=builditems.get_items(bld, sources),
              includes=builditems.get_includes(bld, includes),
              cflags=builditems.get_cflags(bld, cflags),
              asflags=builditems.get_cflags(bld, cflags),
              defines=builditems.get_defines(bld, defines),
              use=[
                  'flare_fs', 'flare_zynqmp_support', 'flare_aarch64_support',
                  'flare_zynq7000_support', 'flare_arm_support'
              ])
